#!/usr/bin/env python3
"""Optimize bundled ClassicAI archive installation in final browser packages.

The platform wrappers intentionally install the bundled AI before and after cloud
restore. The historical implementation decoded every base64 archive before it
checked whether the already-installed file had the same size, so the second pass
always paid another atob()+Uint8Array allocation. This patch makes the size check
allocation-free and lets MEMFS own newly decoded buffers.
"""
from __future__ import annotations

import argparse
from pathlib import Path

TARGETS = ("openttd-yandex-fixes.js", "openttd-playgama-fixes.js")

OLD_HELPER = """  const base64ToBytes = (value) => {
    const raw = atob(value || '');
    const bytes = new Uint8Array(raw.length);
    for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
    return bytes;
  };
"""

NEW_HELPER = """  const base64DecodedLength = (value) => {
    const encoded = String(value || '');
    if (!encoded.length) return 0;
    /* Bundled archives are generated by Python base64.b64encode(), so there is
       no embedded whitespace and the encoded length is always a multiple of 4. */
    if ((encoded.length & 3) !== 0) return -1;
    let padding = 0;
    if (encoded.endsWith('==')) padding = 2;
    else if (encoded.endsWith('=')) padding = 1;
    return Math.max(0, (encoded.length * 3 >> 2) - padding);
  };

  const base64ToBytes = (value) => {
    const raw = atob(value || '');
    const bytes = new Uint8Array(raw.length);
    for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
    return bytes;
  };

  const aiArchiveInstallStats = window.__openttdAIArchiveInstallStats = {
    sizeCheckBeforeDecode: true,
    zeroCopyMemfsWrites: true,
    passes: 0,
    decodedArchives: 0,
    skippedSameSize: 0,
    writes: 0,
  };
"""

OLD_INSTALL = """  const installClassicAI = (FS, personalDir) => {
    const bundle = window.__openttdClassicAIArchives;
    if (!bundle || typeof bundle !== 'object') return;
    for (const [relativePath, encoded] of Object.entries(bundle)) {
      const fullPath = personalDir + '/' + relativePath;
      ensureDir(FS, fullPath.slice(0, fullPath.lastIndexOf('/')));
      try {
        const bytes = base64ToBytes(encoded);
        let same = false;
        try { same = FS.stat(fullPath).size === bytes.length; } catch (_) {}
        if (!same) FS.writeFile(fullPath, bytes);
      } catch (error) {
"""

NEW_INSTALL = """  const installClassicAI = (FS, personalDir) => {
    const bundle = window.__openttdClassicAIArchives;
    if (!bundle || typeof bundle !== 'object') return;
    aiArchiveInstallStats.passes++;
    for (const [relativePath, encoded] of Object.entries(bundle)) {
      const fullPath = personalDir + '/' + relativePath;
      ensureDir(FS, fullPath.slice(0, fullPath.lastIndexOf('/')));
      try {
        const expectedBytes = base64DecodedLength(encoded);
        if (expectedBytes <= 0) throw new Error('Invalid bundled AI base64 length: ' + relativePath);

        let same = false;
        try { same = Number(FS.stat(fullPath).size) === expectedBytes; } catch (_) {}
        if (same) {
          aiArchiveInstallStats.skippedSameSize++;
          continue;
        }

        const bytes = base64ToBytes(encoded);
        aiArchiveInstallStats.decodedArchives++;
        if (bytes.length !== expectedBytes) {
          throw new Error(`Bundled AI decoded-size mismatch for ${relativePath}: ${bytes.length}/${expectedBytes}`);
        }
        FS.writeFile(fullPath, bytes, { canOwn: true });
        aiArchiveInstallStats.writes++;
        const writtenSize = Number(FS.stat(fullPath).size);
        if (writtenSize !== expectedBytes) {
          throw new Error(`Bundled AI write verification failed for ${relativePath}: ${writtenSize}/${expectedBytes}`);
        }
      } catch (error) {
"""


def patch(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    if "__openttdAIArchiveInstallStats" in text:
        required = (
            "sizeCheckBeforeDecode: true",
            "zeroCopyMemfsWrites: true",
            "skippedSameSize++",
            "FS.writeFile(fullPath, bytes, { canOwn: true })",
        )
        if any(marker not in text for marker in required):
            raise SystemExit(f"Partial/invalid AI archive optimization already present in {path}")
        print(f"AI archive install fast path already present: {path.name}")
        return

    if text.count(OLD_HELPER) != 1:
        raise SystemExit(f"Expected one ClassicAI base64 helper in {path}, found {text.count(OLD_HELPER)}")
    if text.count(OLD_INSTALL) != 1:
        raise SystemExit(f"Expected one ClassicAI install prefix in {path}, found {text.count(OLD_INSTALL)}")

    text = text.replace(OLD_HELPER, NEW_HELPER, 1)
    text = text.replace(OLD_INSTALL, NEW_INSTALL, 1)

    required = (
        "__openttdAIArchiveInstallStats",
        "sizeCheckBeforeDecode: true",
        "zeroCopyMemfsWrites: true",
        "aiArchiveInstallStats.passes++",
        "aiArchiveInstallStats.skippedSameSize++",
        "aiArchiveInstallStats.decodedArchives++",
        "FS.writeFile(fullPath, bytes, { canOwn: true })",
        "installClassicAI(FS, personalDir);",
    )
    if any(marker not in text for marker in required):
        raise SystemExit(f"AI archive optimization validation failed for {path}")
    path.write_text(text, encoding="utf-8")
    print(f"Optimized ClassicAI archive installer: {path.name}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("dist", type=Path)
    args = parser.parse_args()
    dist = args.dist.resolve()

    candidates = [dist / name for name in TARGETS if (dist / name).is_file()]
    if len(candidates) != 1:
        raise SystemExit(f"Expected exactly one platform fixes file in {dist}, found {[p.name for p in candidates]}")
    patch(candidates[0])


if __name__ == "__main__":
    main()
